name: Build, Test and Deploy React Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Optionnel : on peut garder workflow_dispatch pour déclencher manuellement
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies and run tests
        run: |
          npm ci
          npm test
        env: 
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}

      - name: Build the application
        run: npm run build
        env: 
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Upload build artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build_test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write      # Permet le déploiement sur GitHub Pages
      id-token: write   # Pour vérifier la provenance du déploiement
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
